services:
  - type: web
    name: fitzone-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PGSSL
        value: 'true'
      - key: PORT
        value: '10000'
    healthCheckPath: /api/health
    autoDeploy: true
